package com.photography.timekeeperbackend.domain.exception;

public enum ErrorCode {
    MEMBER_NOT_FOUND,
    MEMBER_WITHDRAWN,
    LOGIN_ID_DUPLICATED,
    PASSWORD_NOT_MATCHED,
    COHORT_NOT_FOUND,
    PART_NOT_FOUND,
    TEAM_NOT_FOUND,
    COHORT_MEMBER_NOT_FOUND,
    SESSION_NOT_FOUND,
    SESSION_NOT_IN_PROGRESS,
    SESSION_CANCELLED,
    QR_NOT_FOUND,
    QR_INVALID,
    QR_EXPIRED,
    QR_ALREADY_ACTIVE,
    ATTENDANCE_NOT_FOUND,
    ATTENDANCE_ALREADY_CHECKED,
    DEPOSIT_INSUFFICIENT,
    CONCURRENCY_CONFLICT,
    EXCUSE_LIMIT_EXCEEDED,
    INVALID_DOMAIN_VALUE
}
